### ISSUE TITLE
Guide on deploying Contour in multiple namespaces

### ISSUE THREAD

**Issue by jpeach** [knative/net-contour#20]
The current deployment YAML creates 2 Contour deployments in the same namespace. A different approach is to keep them in separate namespaces (e.g. projectcontour-internal and projectcontour-external), which has the benefit that you can generate separate TLS keys for the xDS session.

Here's a worked example using kustomize:

https://github.com/jpeach/kustomize/tree/master/knative/configurations/contour

**Comment by mattmoor** [comment]
We do this now by default, I think more than this should fall on the guide for configuring this for use with your own Contour.
