### ISSUE TITLE
TestVisibility hitting a number of connection refused errors

### ISSUE THREAD

**Issue by mattmoor** [knative/net-contour#70]
With and without split:

```
--- FAIL: TestVisibility (18.02s)
    visibility_test.go:39: [visibility-elozhoiu] Using port 92
    visibility_test.go:39: [visibility-elozhoiu] Using containerPort 8090
    visibility_test.go:64: Error making GET request: Get http://visibility-abfidose.serving-tests.svc.cluster.local: dial tcp 34.71.45.97:80: connect: connection refused
    visibility_test.go:67: [visibility-lmebvknk] Using port 82
    visibility_test.go:67: [visibility-lmebvknk] Using containerPort 8097
--- FAIL: TestVisibilitySplit (97.77s)
    visibility_test.go:108: [visibility-split-bvudnwlc] Using port 79
    visibility_test.go:108: [visibility-split-bvudnwlc] Using containerPort 8058
    visibility_test.go:108: [visibility-split-jwcgooxf] Using port 57
    visibility_test.go:108: [visibility-split-jwcgooxf] Using containerPort 8020
    visibility_test.go:108: [visibility-split-xvjtxrgv] Using port 74
    visibility_test.go:108: [visibility-split-xvjtxrgv] Using containerPort 8094
    visibility_test.go:108: [visibility-split-nsnxvrad] Using port 57
    visibility_test.go:108: [visibility-split-nsnxvrad] Using containerPort 8063
    visibility_test.go:108: [visibility-split-ujvwtfyv] Using port 95
    visibility_test.go:108: [visibility-split-ujvwtfyv] Using containerPort 8034
    visibility_test.go:108: [visibility-split-msrogntp] Using port 96
    visibility_test.go:108: [visibility-split-msrogntp] Using containerPort 8005
    visibility_test.go:108: [visibility-split-rvcscqii] Using port 94
    visibility_test.go:108: [visibility-split-rvcscqii] Using containerPort 8073
    visibility_test.go:108: [visibility-split-jjmjmaej] Using port 92
    visibility_test.go:108: [visibility-split-jjmjmaej] Using containerPort 8007
    visibility_test.go:108: [visibility-split-meudfqwn] Using port 53
    visibility_test.go:108: [visibility-split-meudfqwn] Using containerPort 8096
    visibility_test.go:108: [visibility-split-gwgtbvzt] Using port 97
    visibility_test.go:108: [visibility-split-gwgtbvzt] Using containerPort 8037
    visibility_test.go:152: Error making GET request: Get http://visibility-split-jioorbfb.serving-tests.svc.cluster.local: dial tcp 34.71.45.97:80: connect: connection refused
    visibility_test.go:155: [visibility-split-ikxjnobf] Using port 79
    visibility_test.go:155: [visibility-split-ikxjnobf] Using containerPort 8034
```

@andrew-su are you up for taking a look (I think you added this test)?

**Comment by andrew-su** [comment]
From our investigation, when the ingress has no external traffic configured it seems to refuse connections to port 80 of the ingress.

When this is run as part of the test suite, depending on the parallel tests running there may be a publicly exposed knative ingress resource thus opening port 80 for connection. When running the test by itself, it has a much higher chance of exhibiting the above behaviour.

/cc @shashwathi

**Comment by mattmoor** [comment]
So is the problem that it doesn’t fail the way it “should”?  Isn’t this a perfectly acceptable failure mode?  Test bug?

**Comment by andrew-su** [comment]
Right, the check is not failing the way it should because we were expecting the ingress to respond with a 404 but got a connection refused. This is an acceptable failure in the eyes of the test (not handled). However, the error comes from the client being unable to connect to the envoy proxy since the proxy itself doesn't listen on port 80 if it doesn't have anything to proxy to.

The error of connection refused is difficult to detect as it is returned as a generic error similar to other http client errors; making it hard to differentiate from when we have a legit test failure. 

We could parse the error message and check if it contains "connection refused" but that doesn't seem very correct.

**Comment by mattmoor** [comment]
What is the type of the error?  `Infof("%T", err)`?

I'm wondering if we can check for something like `if _, ok := err.(*net.OpError); ok { // fine`

**Comment by mattmoor** [comment]
IIUC we will need to update-deps and remove the `V` from our `Test[^UV]` line, right?

**Comment by andrew-su** [comment]
> IIUC we will need to update-deps and remove the V from our Test[^UV] line, right?

Yup. (Also, what does `IIUC` stand for?)

**Comment by mattmoor** [comment]
If I Understand Correctly (I also use IIRC a lot, which is "Recall").  Sorry 😬

**Comment by andrew-su** [comment]
Thanks!

Closing because PR is accepted.

/close

**Comment by mattmoor** [comment]
We never removed the test skip.  Sent a PR 😅
